apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-03-12T14:35:13Z"
  name: carts-canary
  resourceVersion: "16895"
  selfLink: /api/v1/namespaces/sockshop-production/services/carts
  uid: af3f4907-646e-11ea-bb4a-42010a8000ae
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: carts
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
